sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ "$CC" = "clang" ]; then 
      sudo apt-get update -qq;
      sudo apt-get install -y libc++1 libc++-dev; 
    fi

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - make VERBOSE=1
