sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        if [ "$CC" = "clang" ]; then 
          sudo apt-get update -qq;
          sudo apt-get install -y libc++1 libc++-dev; 
        fi;
    fi

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - make VERBOSE=1
