language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libstdc++6
  - sudo apt-get install -y libstdc++6-4.4-dev

compiler:
  - clang
  - gcc

script:
  - cmake .
  - cd src
  - make
