#!/bin/bash
#
# This script combines all individual Belgian OpenAir files into one Belgian
# OpenAir file.


OA2PM_ROOTDIR=~/Dropbox/MyProjects/oaconvert
AIRSPACE_DIR=${OA2PM_ROOTDIR}/openair/belgium
OUTPUTFILE=$AIRSPACE_DIR/belgium_autogenerated.txt


AIRSPACES="${AIRSPACE_DIR}/*ctr*.txt
           ${AIRSPACE_DIR}/*tma*.txt
           ${AIRSPACE_DIR}/*cta*.txt
           ${AIRSPACE_DIR}/lfa*.txt"


> $OUTPUTFILE
for file in $AIRSPACES
do
  echo -n "Adding $(basename $file)... "
  cat $file >> $OUTPUTFILE
  echo -ne "\n\n" >> $OUTPUTFILE
  echo "done."
done


${OA2PM_ROOTDIR}/src/oaconvert -o ${OA2PM_ROOTDIR}/cgpsmapper/belgium.mp ${OA2PM_ROOTDIR}/openair/belgium/belgium_autogenerated.txt
${OA2PM_ROOTDIR}/src/oaconvert -o ${OA2PM_ROOTDIR}/cgpsmapper/belgium.gpx ${OA2PM_ROOTDIR}/openair/belgium/belgium_autogenerated.txt
