#include "header.h"
#include <fstream>
using namespace std;

void Header::writeHeader() {

  ofstream outStream;

  outStream.open("output.mp");

  outStream << "; Generated by oa2pm (OpenAir to Polish Format converter)\n";
  outStream << "[IMG ID]\n";
  outStream << "ID=42200100\n";
  outStream << "Name=air Slovakia from_sfc 2003\n";
  outStream << "Preprocess=F\n";
  outStream << "CodePage=1250\n";
  outStream << "TreSize=1311\n";
  outStream << "POIIndex=N\n";
  outStream << "Levels=5\n";
  outStream << "Level0=21\n";
  outStream << "Level1=19\n";
  outStream << "Level2=17\n";
  outStream << "Level3=15\n";
  outStream << "Level4=14\n";
  outStream << "Zoom0=0\n";
  outStream << "Zoom1=1\n";
  outStream << "Zoom2=2\n";
  outStream << "Zoom3=3\n";
  outStream << "Zoom4=4\n";
  outStream << "[END-IMG ID]";

  outStream.close();

}
