#include "header.h"
#include <fstream>
using namespace std;

void Header::write() {

  ofstream outStream;

  outStream.open("output.mp");

  outStream << "; Generated by oa2pm (OpenAir to Polish Format converter)\n";

  // Section identifier (mandatory).
  outStream << "[IMG ID]\n";

  // Unique identifier (up to 8 decimal digits) for the map (mandatory).  May
  // be only written in a decimal format.  The cgpsmapper manual gives has as
  // an example an ID=11000204 so that is the one we use.  In the oa2pm source
  // code, the value 42200100 is used.
  outStream << "ID=11000204\n";

  // Map name to be displayed in the GPS receiver's Map Info menu (mandatory).
  outStream << "Name=My Very Special Map\n";

  // Instead of single byte coding, use full-byte (8-bit) character coding
  // with the specified codepage (depending on the GPS firmware) (optional).
  // We use the default of 0 here, but the oa2gm source code has a value
  // of 1250, probably because the author needed it (see for example
  // http://en.wikipedia.org/wiki/Windows-1250 ).
  outStream << "Codepage=0\n";

  // Only index objects if POI index info is explicitly provided.  With
  // 'indexing', we mean 'make searcheable by the Find function in the GPS'.
  // We follow the default value  of 'N' here.
  outStream << "POIIndex=N\n";

  // Maximum allowed region size.  A higher value increases the allowable
  // region size, but may decrease the map performance; a lower value may
  // increase the map size.
  // Suggested values:
  //   topo maps: 1000-2000
  //   city (dense streets): 2000-5000
  //   countryside: 6000-10000
  outStream << "TreSize=1311\n";

  // Maximal number of elements in one region (mandatory).
  // Can be any value between ~50 and 1024 (values less than 50 don't make
  // sense).  Recent experiments show that this parameter does not impact
  // map performance and can be set to maximum allowed value: 1024.
  // Suggested value: 1024
  outStream << "RgnLimit=1024\n";

  // Kind of pre-processing.  We're setting it to the default here...
  outStream << "PreProcess=F\n";

  // Number of levels (layers) in the map (at least 2, not more than 10)
  // (mandatory).
  // Note: the last layer must always be empty, e.g. Levels=3
  //       means that two layers only are available for map objects.
  outStream << "Levels=5\n";

  // See section 4.4 (on page 40) of cgpsmapper manual (mandatory).
  outStream << "Level0=21\n";
  outStream << "Level1=19\n";
  outStream << "Level2=17\n";
  outStream << "Level3=15\n";
  outStream << "Level4=14\n";

  // See section 4.4 (on page 40) of cgpsmapper manual (mandatory)
  outStream << "Zoom0=0\n";
  outStream << "Zoom1=1\n";
  outStream << "Zoom2=2\n";
  outStream << "Zoom3=3\n";
  outStream << "Zoom4=4\n";

  // Section terminator (mandatory)
  outStream << "[END-IMG ID]";

  outStream.close();

}
