#include "PolishState.h"

#include <cassert>
#include "airspace.h"
#include "Circle.h"
#include "CurvedPolygon.h"

using namespace std;
using namespace Constants;

PolishState* PolishState::_instance = 0;

PolishState::PolishState()
  {
  }

PolishState* PolishState::getInstance()
  {
  if (_instance == 0)
    {
    _instance = new PolishState;
    }
  return _instance;
  }

void PolishState::writeHeader(std::ostream &out) const
  {

  out << "; Generated by oa2pm (OpenAir to Polish Format converter)\n";

  // Section identifier (mandatory).
  out << "[IMG ID]" << endl;

  // Unique identifier (up to 8 decimal digits) for the map (mandatory).  May
  // be only written in a decimal format.  The cgpsmapper manual gives has as
  // an example an ID=11000204 so that is the one we use.  In the oa2pm source
  // code, the value 42200100 is used.
  out << "ID=11000204" << endl;

  // Map name to be displayed in the GPS receiver's Map Info menu (mandatory).
  out << "Name=My Very Special Map" << endl;

  // Instead of single byte coding, use full-byte (8-bit) character coding
  // with the specified codepage (depending on the GPS firmware) (optional).
  // We use the default of 0 here, but the oa2gm source code has a value
  // of 1250, probably because the author needed it (see for example
  // http://en.wikipedia.org/wiki/Windows-1250 ).
  out << "Codepage=0" << endl;

  // Only index objects if POI index info is explicitly provided.  With
  // 'indexing', we mean 'make searcheable by the Find function in the GPS'.
  // We follow the default value  of 'N' here.
  out << "POIIndex=N" << endl;

  // Maximum allowed region size.  A higher value increases the allowable
  // region size, but may decrease the map performance; a lower value may
  // increase the map size.
  // Suggested values:
  //   topo maps: 1000-2000
  //   city (dense streets): 2000-5000
  //   countryside: 6000-10000
  out << "TreSize=1311" << endl;

  // Maximal number of elements in one region (mandatory).
  // Can be any value between ~50 and 1024 (values less than 50 don't make
  // sense).  Recent experiments show that this parameter does not impact
  // map performance and can be set to maximum allowed value: 1024.
  // Suggested value: 1024
  out << "RgnLimit=1024" << endl;

  // Kind of pre-processing.  We're setting it to the default here...
  out << "PreProcess=F" << endl;


  // This is what oa2gm uses, but it didn't work with GPSMapEdit 1.0.70.0.
  //out << "Levels=5\n";
  //out << "Level0=21\n";
  //out << "Level1=19\n";
  //out << "Level2=17\n";
  //out << "Level3=15\n";
  //out << "Level4=14\n";
  //out << "Zoom0=0\n";
  //out << "Zoom1=1\n";
  //out << "Zoom2=2\n";
  //out << "Zoom3=3\n";
  //out << "Zoom4=4\n";


  // Below is what GPSMapEdit 1.0.69.1 outputs, and it seems to work in
  // GPSMapEdit... so we use this.  Note that this might not work as fluently
  // on actual GPS units like the Garmin 60CSX.

  // Note 1: the last layer must always be empty, e.g. Levels=3
  //         means that two layers only are available for map objects.
  // Note 2: GPS unit map detail must be set to 'Normal'!!!!!
  // See section 4.4 (on page 40) of cgpsmapper manual (mandatory).

  // Number of map zoom levels (layers) in the map (mandatory, at least 2,
  // not more than 10, numbered starting at 0).
  out << "Levels=2" << endl;

  // Map zoom level 0 corresponds to hardware zoom level 24 ('Up to 120m')
  // This means that map objects and coordinates defined as map level 0, will
  // be used at hardware zoom levels 24 and above.  So they will be visible
  // if the scale is 120m or more detailed.
  out << "Level0=24" << endl;

  // Last level is a special one that dictates when our map replaces the
  // base map.  It means the following: from hardware level
  // 14 ('80km to 120 km') or higher, we will see our map.  At hardware
  // zoom levels 13 and below, we will see the base map.
  // We are not allowed to define map objects and coordinates at this level.
  out << "Level1=14" << endl;

  out << "Zoom0=0" << endl;
  out << "Zoom1=1" << endl;


  // Section terminator (mandatory)
  out << "[END-IMG ID]\n" << endl;
  }

void PolishState::writeFooter(std::ostream &out) const
  {
  // TODO
  }


// void PolishState::write(ostream& out, const AirSpace& s) const
// {
//   /* TODO
//   if ( s.hasPolygon() )
//   {
//     //cout << "DEBUG: Airspace has a polygon" << endl;
//     write(out, s.getPolygon(), s.getName());
//   }
//   if ( s.hasCircle() )
//   {
//     //cout << "DEBUG: Airspace has a circle" << endl;
//     write(out, s.getCircle().toPolygon(100), s.getName());;
//   }
//   */
// }

void PolishState::write(std::ostream& stream, const AirSpace& airspace) const
  {
  std::cout << "PolishState::write(AirSpace)" << std::endl;

  if( ! airspace.getRegion() )
    {
    std::cout << " WARNING: Not printing airspace with empty region." << std::endl;
    return;
    }

  // See section 4.2.4.2 in http://cgpsmapper.com/download/cGPSmapper-UsrMan-v02.1.pdf

  // oa2gm used [RGN40] here, which is a [POLYLINE]... I think one could also
  // use [RGN80] here, which is a [POLYGON].
  stream << "[POLYGON]" << endl;
  // Type of [POLYGON] element: 'Airport'
  // We should probably change this to something which is more appropriate
  // for each earspace separately.
  // See section 12.3.3 in the cgpsmapper manual.
  // Note that oa2gm used Type=0x0a which is an 'Unpaved Road-thin', but this
  // is for [POLYLINE], not [POLYGON]...
  stream << "Type=0x07" << endl;

  stream << "Label=" << airspace.getName() << endl;
  OutputState::write(stream, airspace.getRegion());
  }

void PolishState::write(std::ostream& stream, const Circle* circle) const
  {
  cout << "PolishState::write(Circle)" << endl;
  std::vector<Coordinate> coords;
  // TODO: check what resolution to use!
  circle->discretize( coords, 1 );
  write( stream, coords );
//    write(s.getCircle().toPolygon(NBPOINTS), s.getName());;
//  assert( ! "TODO" );
  }

void PolishState::write(std::ostream& stream, const CurvedPolygon* curved_polygon) const
  {
  cout << "PolishState::write(CurvedPolygon)" << endl;
  std::vector<Coordinate> coords;
  // TODO: check what resolution to use!
  curved_polygon->discretize( coords, 1 );
  write( stream, coords );
//  assert( ! "TODO" );
  }


void PolishState::write(ostream& out, const Coordinate& c) const
{
  out << "(" << c.getLatitude().getAngle() << "," << c.getLongitude().getAngle() << ")";
}


void PolishState::write(std::ostream& out, const std::vector<Coordinate>& coords) const
{
  if (coords.size() > 0)
  {
    out << "Data0=";
    for (size_t i = 1; i< coords.size(); ++i)
    {
      write(out, coords[i]);
      out << ",";
    }
    {
      write(out, coords.back());
    }
    out << endl;
  }
  out << "[END]\n" << endl;
}
